apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-runner
  labels:
    app: java-runner
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-runner
      tier: backend
  template:
    metadata:
      labels:
        app: java-runner
        tier: backend
    spec:
      containers:
        - name:  java-runner
          image:  zerows/java-runner:latest
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: url
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: password
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: queue-conf
                  key: host
            - name: QUEUE_NAME
              value: "java"
            - name: QUEUE_PORT
              value: "5672"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-runner
  labels:
    app: ruby-runner
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-runner
      tier: backend
  template:
    metadata:
      labels:
        app: ruby-runner
        tier: backend
    spec:
      containers:
        - name:  ruby-runner
          image:  zerows/ruby-runner:latest
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: url
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: password
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: queue-conf
                  key: host
            - name: QUEUE_NAME
              value: "ruby"
            - name: QUEUE_PORT
              value: "5672"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: javascript-runner
  labels:
    app: javascript-runner
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javascript-runner
      tier: backend
  template:
    metadata:
      labels:
        app: javascript-runner
        tier: backend
    spec:
      containers:
        - name:  javascript-runner
          image:  zerows/javascript-runner:latest
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: url
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: password
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: queue-conf
                  key: host
            - name: QUEUE_NAME
              value: "javascript"
            - name: QUEUE_PORT
              value: "5672"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-runner
  labels:
    app: python-runner
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-runner
      tier: backend
  template:
    metadata:
      labels:
        app: python-runner
        tier: backend
    spec:
      containers:
        - name:  python-runner
          image:  zerows/python-runner:latest
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: url
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: password
            - name: QUEUE_HOST
              valueFrom:
                configMapKeyRef:
                  name: queue-conf
                  key: host
            - name: QUEUE_NAME
              value: "python"
            - name: QUEUE_PORT
              value: "5672"