apiVersion: v1
kind: Service
metadata:
  name: postgres #DNS
  labels:
    app: postgres
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    tier: database
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce #Makes sure the volume is mounted only once by the PODS
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: posrgres
        tier: database
    spec:
      containers:
        - image: postgres:12.2  # image from docker-hub
          name: postgres
          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: name
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: db-conf
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          ports:
          - containerPort: 5432
            name: postgres
          volumeMounts:
            - name: pg-persistent-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: pg-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

