apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress"
spec:
  rules:
    - host: zingseven.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: web-app
              servicePort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress-socket
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress"
spec:
  rules:
    - host: socket.zingseven.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: socket-app
              servicePort: 80