apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress
spec:
  rules:
    - host: socket.code-fry.in
      http:
        paths:
          - backend:
              serviceName: socket-app
              servicePort: 80
    - host: code-fry.in
      http:
        paths:
          - backend:
              serviceName: web-app
              servicePort: 80