apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress
spec:
  rules:
    - host: zingseven.com
      http:
        paths:
          - backend:
              serviceName: web-app
              servicePort: 80