apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: zingseven.com/sockets
      http:
        paths:
          - backend:
              serviceName: socket-app
              servicePort: 80
            path: /
