apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
    - host: www.zingseven.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: web-app
              servicePort: 80