apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: exposed-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: zingseven.com
      http:
        paths:
          - path: /
            backend:
              serviceName: web-app
              servicePort: 80