apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    app: codefry-web
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: codefry-web
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codefry-web
      tier: frontend
  template:
    metadata:
      labels:
        app: codefry-web
        tier: frontend
    spec:
      containers:
        - name:  web-app
          image:  shrikanthkr/test-kuber:latest
          command: ["/bin/sh", "entrypoint.sh"]
          env:
            - name: RAILS_ENV
              value: production
            - name: SECRET_KEY_BASE
              value: 17b251d7a3645316e6f6688ff66263b997dc26419bf1bbbf2cb2678f6d085172668e802ebe7efc8f5dde155a68cc2217dd9995742c481f5fdf9a1bf5cc92b295
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 3000
