version: "2"
services:
  web:
    build: .
    container_name: "code-fry-app"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    links:
      - db
      - rmq
    depends_on:
      - db
      - rmq
    command: ["./wait.sh","rabbitmq:5672 ","--", "rails", "s"]
  rmq:
    image: rabbitmq
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
  db:
    image: postgres
    restart: always
    container_name: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./test_data:/test_data
      - ./data/postgres:/var/lib/postgresql/data
