version: "3.7"
services:
  web:
    build: .
    container_name: "code-fry-app"
    volumes:
      - ./:/app
      - pg-volume:/var/run/postgresql/
      - node_modules:/app/frontend/node_modules
      - bundle_volume:/bundle
    environment:
      - NODE_ENV=development
      - BUNDLE_PATH=/bundle/vendor
    ports:
      - "3000:3000"
      - "1234:1234"
    links:
      - db
      - rmq
    depends_on:
      - db
      - rmq
      - sockets
    command: ["./wait.sh","rabbitmq:5672 ","--", "./dev_server_start.sh"]
  rmq:
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
  db:
    restart: always
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./test_data:/test_data
      - ./data/postgres:/var/lib/postgresql/data
      - pg-volume:/var/run/postgresql/
  sockets:
    build: ./fry-code-sockets
    container_name: sockets
    ports:
      - "4500:4500"
    environment:
      - NODE_ENV=development
      - PORT=4500

volumes:
  pg-volume:
  node_modules:
  bundle_volume:
