version: "3.7"
services:
  web:
    build: .
    container_name: "code-fry-app"
    restart: always
    volumes:
      - ./:/app
      - pg-volume:/var/run/postgresql/
      - node_modules:/app/frontend/node_modules
    environment:
      - NODE_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - "3000:3000"
    links:
      - db
      - rmq
    depends_on:
      - db
      - rmq
    command: ["./wait.sh","rabbitmq:5672 ","--", "./server_start.sh"]
  rmq:
    image: rabbitmq
    restart: always
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
  db:
    image: postgres
    container_name: "postgres"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - pg-volume:/var/run/postgresql/

volumes:
  pg-volume:
  node_modules: