version: "2"
services:
  web:
    build: .
    container_name: "code-fry-app"
    volumes:
      - ./:/app
      - ./var/run/postgresql/:/var/run/postgresql/
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "1234:1234"
    links:
      - db
      - rmq
    depends_on:
      - db
      - rmq
    command: ["./wait.sh","rabbitmq:5672 ","--", "./server_start.sh"]
  rmq:
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
  db:
    restart: always
    container_name: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./test_data:/test_data
      - ./data/postgres:/var/lib/postgresql/data
      - ./var/run/postgresql/:/var/run/postgresql/
