version: "2"
services:
  web:
    build: .
    container_name: "code-fry-app"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres
    restart: always
    container_name: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./test_data:/test_data
      - ./data/postgres:/var/lib/postgresql/data
