version: "3.7"
services:
  web:
    build: .
    container_name: "code-fry-app"
    volumes:
      - ./:/app
      - pg-volume:/var/run/postgresql/
      - gembox:/box
      - node_modules:/app/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "1234:1234"
    links:
      - db
      - rmq
    depends_on:
      - db
      - rmq
      - box
    command: ["./wait.sh","rabbitmq:5672 ","--", "./dev_server_start.sh"]
  rmq:
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
  db:
    restart: always
    container_name: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./test_data:/test_data
      - ./data/postgres:/var/lib/postgresql/data
      - pg-volume:/var/run/postgresql/
  box:
    image: busybox
    volumes:
      - gembox:/box

volumes:
  pg-volume:
  gembox:
  node_modules:
